/**
 * Orchestra API
 * API to edit FIX Orchestra (machine readable rules of engagement) specification version 1.0 RC3
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Annotation from './Annotation';
import Structure from './Structure';





/**
* The Actor model module.
* @module model/Actor
* @version 1.0.0
*/
export default class Actor {
    /**
    * Constructs a new <code>Actor</code>.
    * Represents a class of participants
    * @alias module:model/Actor
    * @class
    * @param name {String} unique name
    */

    constructor(name) {
        

        
        

        this['name'] = name;

        
    }

    /**
    * Constructs a <code>Actor</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Actor} obj Optional instance to populate.
    * @return {module:model/Actor} The populated <code>Actor</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Actor();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('extends')) {
                obj['extends'] = ApiClient.convertToType(data['extends'], 'String');
            }
            if (data.hasOwnProperty('structure')) {
                obj['structure'] = Structure.constructFromObject(data['structure']);
            }
            if (data.hasOwnProperty('annotation')) {
                obj['annotation'] = Annotation.constructFromObject(data['annotation']);
            }
        }
        return obj;
    }

    /**
    * unique name
    * @member {String} name
    */
    name = undefined;
    /**
    * Inherits properties from another Actor
    * @member {String} extends
    */
    extends = undefined;
    /**
    * State variables
    * @member {module:model/Structure} structure
    */
    structure = undefined;
    /**
    * @member {module:model/Annotation} annotation
    */
    annotation = undefined;








}


