/**
 * Orchestra API
 * API to edit FIX Orchestra (machine readable rules of engagement) specification version 1.0 RC3
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Appinfo from './Appinfo';
import Documentation from './Documentation';





/**
* The Annotation model module.
* @module model/Annotation
* @version 1.0.1
*/
export default class Annotation {
    /**
    * Constructs a new <code>Annotation</code>.
    * @alias module:model/Annotation
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Annotation</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Annotation} obj Optional instance to populate.
    * @return {module:model/Annotation} The populated <code>Annotation</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Annotation();

            
            
            

            if (data.hasOwnProperty('appinfo')) {
                obj['appinfo'] = ApiClient.convertToType(data['appinfo'], [Appinfo]);
            }
            if (data.hasOwnProperty('documentation')) {
                obj['documentation'] = ApiClient.convertToType(data['documentation'], [Documentation]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/Appinfo>} appinfo
    */
    appinfo = undefined;
    /**
    * @member {Array.<module:model/Documentation>} documentation
    */
    documentation = undefined;








}


