/**
 * Orchestra API
 * API to edit FIX Orchestra (machine readable rules of engagement) specification version 1.0 RC3
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Annotation from './Annotation';
import Code from './Code';
import EntityAttributes from './EntityAttributes';
import ObjectId from './ObjectId';





/**
* The CodeSet model module.
* @module model/CodeSet
* @version 1.0.1
*/
export default class CodeSet {
    /**
    * Constructs a new <code>CodeSet</code>.
    * @alias module:model/CodeSet
    * @class
    * @param oid {module:model/ObjectId} 
    * @param type {String} 
    */

    constructor(oid, type) {
        

        
        

        this['oid'] = oid;this['type'] = type;

        
    }

    /**
    * Constructs a <code>CodeSet</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CodeSet} obj Optional instance to populate.
    * @return {module:model/CodeSet} The populated <code>CodeSet</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CodeSet();

            
            
            

            if (data.hasOwnProperty('oid')) {
                obj['oid'] = ObjectId.constructFromObject(data['oid']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('specURL')) {
                obj['specURL'] = ApiClient.convertToType(data['specURL'], 'String');
            }
            if (data.hasOwnProperty('default')) {
                obj['default'] = ApiClient.convertToType(data['default'], 'String');
            }
            if (data.hasOwnProperty('codes')) {
                obj['codes'] = ApiClient.convertToType(data['codes'], [Code]);
            }
            if (data.hasOwnProperty('annotation')) {
                obj['annotation'] = Annotation.constructFromObject(data['annotation']);
            }
            if (data.hasOwnProperty('entityAttributes')) {
                obj['entityAttributes'] = EntityAttributes.constructFromObject(data['entityAttributes']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/ObjectId} oid
    */
    oid = undefined;
    /**
    * @member {String} type
    */
    type = undefined;
    /**
    * @member {String} specURL
    */
    specURL = undefined;
    /**
    * @member {String} default
    */
    default = undefined;
    /**
    * @member {Array.<module:model/Code>} codes
    */
    codes = undefined;
    /**
    * @member {module:model/Annotation} annotation
    */
    annotation = undefined;
    /**
    * @member {module:model/EntityAttributes} entityAttributes
    */
    entityAttributes = undefined;








}


