/**
 * Orchestra API
 * API to edit FIX Orchestra (machine readable rules of engagement) specification version 1.0 RC3
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Annotation from './Annotation';
import EntityAttributes from './EntityAttributes';
import MessageElement from './MessageElement';
import ObjectId from './ObjectId';
import Structure from './Structure';





/**
* The Component model module.
* @module model/Component
* @version 1.0.0
*/
export default class Component {
    /**
    * Constructs a new <code>Component</code>.
    * @alias module:model/Component
    * @class
    * @extends module:model/MessageElement
    * @param oid {module:model/ObjectId} 
    * @param structure {module:model/Structure} 
    */

    constructor(oid, structure) {
        

        MessageElement.call(this, oid);
        

        this['structure'] = structure;

        
    }

    /**
    * Constructs a <code>Component</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Component} obj Optional instance to populate.
    * @return {module:model/Component} The populated <code>Component</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Component();

            

            MessageElement.constructFromObject(data, obj);
            

            if (data.hasOwnProperty('structure')) {
                obj['structure'] = Structure.constructFromObject(data['structure']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Structure} structure
    */
    structure = undefined;








}


