/**
 * Orchestra API
 * API to edit FIX Orchestra (machine readable rules of engagement) specification version 1.0 RC3
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Annotation from './Annotation';
import ElementRef from './ElementRef';
import EntityAttributes from './EntityAttributes';
import ObjectId from './ObjectId';





/**
* The ComponentRef model module.
* @module model/ComponentRef
* @version 1.0.0
*/
export default class ComponentRef {
    /**
    * Constructs a new <code>ComponentRef</code>.
    * @alias module:model/ComponentRef
    * @class
    * @extends module:model/ElementRef
    * @param oid {module:model/ObjectId} 
    */

    constructor(oid) {
        

        ElementRef.call(this, oid);
        

        

        
    }

    /**
    * Constructs a <code>ComponentRef</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ComponentRef} obj Optional instance to populate.
    * @return {module:model/ComponentRef} The populated <code>ComponentRef</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ComponentRef();

            

            ElementRef.constructFromObject(data, obj);
            

        }
        return obj;
    }









}


