/**
 * Orchestra API
 * API to edit FIX Orchestra (machine readable rules of engagement) specification version 1.0 RC3
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Documentation model module.
* @module model/Documentation
* @version 1.0.0
*/
export default class Documentation {
    /**
    * Constructs a new <code>Documentation</code>.
    * @alias module:model/Documentation
    * @class
    * @param text {String} text of Documentation
    */

    constructor(text) {
        

        
        

        this['text'] = text;

        
    }

    /**
    * Constructs a <code>Documentation</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Documentation} obj Optional instance to populate.
    * @return {module:model/Documentation} The populated <code>Documentation</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Documentation();

            
            
            

            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('langId')) {
                obj['langId'] = ApiClient.convertToType(data['langId'], 'String');
            }
            if (data.hasOwnProperty('purpose')) {
                obj['purpose'] = ApiClient.convertToType(data['purpose'], 'String');
            }
        }
        return obj;
    }

    /**
    * text of Documentation
    * @member {String} text
    */
    text = undefined;
    /**
    * a language code (ISO 639-1)
    * @member {String} langId
    */
    langId = undefined;
    /**
    * @member {String} purpose
    */
    purpose = undefined;








}


