/**
 * Orchestra API
 * API to edit FIX Orchestra (machine readable rules of engagement) specification version 1.0 RC3
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Annotation from './Annotation';
import EntityAttributes from './EntityAttributes';
import MessageElement from './MessageElement';
import ObjectId from './ObjectId';





/**
* The Field model module.
* @module model/Field
* @version 1.0.1
*/
export default class Field {
    /**
    * Constructs a new <code>Field</code>.
    * @alias module:model/Field
    * @class
    * @extends module:model/MessageElement
    * @param oid {module:model/ObjectId} 
    * @param type {String} 
    */

    constructor(oid, type) {
        

        MessageElement.call(this, oid);
        

        this['type'] = type;

        
    }

    /**
    * Constructs a <code>Field</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Field} obj Optional instance to populate.
    * @return {module:model/Field} The populated <code>Field</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Field();

            

            MessageElement.constructFromObject(data, obj);
            

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} type
    */
    type = undefined;








}


