/**
 * Orchestra API
 * API to edit FIX Orchestra (machine readable rules of engagement) specification version 1.0 RC3
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The GroupProperties model module.
* @module model/GroupProperties
* @version 1.0.1
*/
export default class GroupProperties {
    /**
    * Constructs a new <code>GroupProperties</code>.
    * @alias module:model/GroupProperties
    * @class
    * @param numInGroupId {Number} 
    * @param numInGroupName {String} 
    */

    constructor(numInGroupId, numInGroupName) {
        

        
        

        this['numInGroupId'] = numInGroupId;this['numInGroupName'] = numInGroupName;

        
    }

    /**
    * Constructs a <code>GroupProperties</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/GroupProperties} obj Optional instance to populate.
    * @return {module:model/GroupProperties} The populated <code>GroupProperties</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GroupProperties();

            
            
            

            if (data.hasOwnProperty('numInGroupId')) {
                obj['numInGroupId'] = ApiClient.convertToType(data['numInGroupId'], 'Number');
            }
            if (data.hasOwnProperty('numInGroupName')) {
                obj['numInGroupName'] = ApiClient.convertToType(data['numInGroupName'], 'String');
            }
            if (data.hasOwnProperty('implMinOccurs')) {
                obj['implMinOccurs'] = ApiClient.convertToType(data['implMinOccurs'], 'Number');
            }
            if (data.hasOwnProperty('implMaxOccurs')) {
                obj['implMaxOccurs'] = ApiClient.convertToType(data['implMaxOccurs'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} numInGroupId
    */
    numInGroupId = undefined;
    /**
    * @member {String} numInGroupName
    */
    numInGroupName = undefined;
    /**
    * @member {Number} implMinOccurs
    */
    implMinOccurs = undefined;
    /**
    * @member {Number} implMaxOccurs
    */
    implMaxOccurs = undefined;








}


