/**
 * Orchestra API
 * API to edit FIX Orchestra (machine readable rules of engagement) specification version 1.0 RC3
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Annotation from './Annotation';
import Component from './Component';
import EntityAttributes from './EntityAttributes';
import GroupProperties from './GroupProperties';
import ObjectId from './ObjectId';
import Structure from './Structure';





/**
* The Group model module.
* @module model/Group
* @version 1.0.1
*/
export default class Group {
    /**
    * Constructs a new <code>Group</code>.
    * @alias module:model/Group
    * @class
    * @extends module:model/Component
    * @param oid {module:model/ObjectId} 
    * @param structure {module:model/Structure} 
    * @param groupProperties {module:model/GroupProperties} 
    */

    constructor(oid, structure, groupProperties) {
        

        Component.call(this, oid, structure);
        

        this['groupProperties'] = groupProperties;

        
    }

    /**
    * Constructs a <code>Group</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Group} obj Optional instance to populate.
    * @return {module:model/Group} The populated <code>Group</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Group();

            

            Component.constructFromObject(data, obj);
            

            if (data.hasOwnProperty('groupProperties')) {
                obj['groupProperties'] = GroupProperties.constructFromObject(data['groupProperties']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/GroupProperties} groupProperties
    */
    groupProperties = undefined;








}


