/**
 * Orchestra API
 * API to edit FIX Orchestra (machine readable rules of engagement) specification version 1.0 RC3
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Annotation from './Annotation';
import EntityAttributes from './EntityAttributes';
import ObjectId from './ObjectId';





/**
* The MessageElement model module.
* @module model/MessageElement
* @version 1.0.1
*/
export default class MessageElement {
    /**
    * Constructs a new <code>MessageElement</code>.
    * @alias module:model/MessageElement
    * @class
    * @param oid {module:model/ObjectId} 
    */

    constructor(oid) {
        

        
        

        this['oid'] = oid;

        
    }

    /**
    * Constructs a <code>MessageElement</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MessageElement} obj Optional instance to populate.
    * @return {module:model/MessageElement} The populated <code>MessageElement</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessageElement();

            
            
            

            if (data.hasOwnProperty('oid')) {
                obj['oid'] = ObjectId.constructFromObject(data['oid']);
            }
            if (data.hasOwnProperty('annotation')) {
                obj['annotation'] = Annotation.constructFromObject(data['annotation']);
            }
            if (data.hasOwnProperty('entityAttributes')) {
                obj['entityAttributes'] = EntityAttributes.constructFromObject(data['entityAttributes']);
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/ObjectId} oid
    */
    oid = undefined;
    /**
    * @member {module:model/Annotation} annotation
    */
    annotation = undefined;
    /**
    * @member {module:model/EntityAttributes} entityAttributes
    */
    entityAttributes = undefined;
    /**
    * @member {String} category
    */
    category = undefined;








}


