/**
 * Orchestra API
 * API to edit FIX Orchestra (machine readable rules of engagement) specification version 1.0 RC3
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The MessageRef model module.
* @module model/MessageRef
* @version 1.0.0
*/
export default class MessageRef {
    /**
    * Constructs a new <code>MessageRef</code>.
    * @alias module:model/MessageRef
    * @class
    * @param name {String} 
    */

    constructor(name) {
        

        
        

        this['name'] = name;

        
    }

    /**
    * Constructs a <code>MessageRef</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MessageRef} obj Optional instance to populate.
    * @return {module:model/MessageRef} The populated <code>MessageRef</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessageRef();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('msgType')) {
                obj['msgType'] = ApiClient.convertToType(data['msgType'], 'String');
            }
            if (data.hasOwnProperty('scenario')) {
                obj['scenario'] = ApiClient.convertToType(data['scenario'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} msgType
    */
    msgType = undefined;
    /**
    * Use case of a message type
    * @member {String} scenario
    * @default 'base'
    */
    scenario = 'base';








}


