/**
 * Orchestra API
 * API to edit FIX Orchestra (machine readable rules of engagement) specification version 1.0 RC3
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ObjectId model module.
* @module model/ObjectId
* @version 1.0.0
*/
export default class ObjectId {
    /**
    * Constructs a new <code>ObjectId</code>.
    * @alias module:model/ObjectId
    * @class
    * @param name {String} Name, unique within a file
    * @param id {Number} Numeric ID, unique within a file, e.g. a field tag
    */

    constructor(name, id) {
        

        
        

        this['name'] = name;this['id'] = id;

        
    }

    /**
    * Constructs a <code>ObjectId</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ObjectId} obj Optional instance to populate.
    * @return {module:model/ObjectId} The populated <code>ObjectId</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ObjectId();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('abbrName')) {
                obj['abbrName'] = ApiClient.convertToType(data['abbrName'], 'String');
            }
            if (data.hasOwnProperty('oid')) {
                obj['oid'] = ApiClient.convertToType(data['oid'], 'String');
            }
        }
        return obj;
    }

    /**
    * Name, unique within a file
    * @member {String} name
    */
    name = undefined;
    /**
    * Numeric ID, unique within a file, e.g. a field tag
    * @member {Number} id
    */
    id = undefined;
    /**
    * Short name
    * @member {String} abbrName
    */
    abbrName = undefined;
    /**
    * Globally unique object identifier, a URI or UUID
    * @member {String} oid
    */
    oid = undefined;








}


