/**
 * Orchestra API
 * API to edit FIX Orchestra (machine readable rules of engagement) specification version 1.0 RC3
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Annotation from './Annotation';
import Transition from './Transition';





/**
* The State model module.
* @module model/State
* @version 1.0.0
*/
export default class State {
    /**
    * Constructs a new <code>State</code>.
    * @alias module:model/State
    * @class
    * @param name {String} 
    */

    constructor(name) {
        

        
        

        this['name'] = name;

        
    }

    /**
    * Constructs a <code>State</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/State} obj Optional instance to populate.
    * @return {module:model/State} The populated <code>State</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new State();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('transitions')) {
                obj['transitions'] = ApiClient.convertToType(data['transitions'], [Transition]);
            }
            if (data.hasOwnProperty('annotation')) {
                obj['annotation'] = Annotation.constructFromObject(data['annotation']);
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {Array.<module:model/Transition>} transitions
    */
    transitions = undefined;
    /**
    * @member {module:model/Annotation} annotation
    */
    annotation = undefined;








}


