/**
 * Orchestra API
 * API to edit FIX Orchestra (machine readable rules of engagement) specification version 1.0 RC3
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Annotation from './Annotation';
import State from './State';





/**
* The StateMachine model module.
* @module model/StateMachine
* @version 1.0.1
*/
export default class StateMachine {
    /**
    * Constructs a new <code>StateMachine</code>.
    * @alias module:model/StateMachine
    * @class
    * @param name {String} 
    */

    constructor(name) {
        

        
        

        this['name'] = name;

        
    }

    /**
    * Constructs a <code>StateMachine</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/StateMachine} obj Optional instance to populate.
    * @return {module:model/StateMachine} The populated <code>StateMachine</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StateMachine();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('initial')) {
                obj['initial'] = State.constructFromObject(data['initial']);
            }
            if (data.hasOwnProperty('states')) {
                obj['states'] = ApiClient.convertToType(data['states'], [State]);
            }
            if (data.hasOwnProperty('annotation')) {
                obj['annotation'] = Annotation.constructFromObject(data['annotation']);
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {module:model/State} initial
    */
    initial = undefined;
    /**
    * @member {Array.<module:model/State>} states
    */
    states = undefined;
    /**
    * @member {module:model/Annotation} annotation
    */
    annotation = undefined;








}


