/**
 * Orchestra API
 * API to edit FIX Orchestra (machine readable rules of engagement) specification version 1.0 RC3
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ComponentRef from './ComponentRef';
import FieldRef from './FieldRef';
import GroupRef from './GroupRef';





/**
* The Structure model module.
* @module model/Structure
* @version 1.0.1
*/
export default class Structure {
    /**
    * Constructs a new <code>Structure</code>.
    * @alias module:model/Structure
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Structure</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Structure} obj Optional instance to populate.
    * @return {module:model/Structure} The populated <code>Structure</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Structure();

            
            
            

            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], [FieldRef]);
            }
            if (data.hasOwnProperty('components')) {
                obj['components'] = ApiClient.convertToType(data['components'], [ComponentRef]);
            }
            if (data.hasOwnProperty('groups')) {
                obj['groups'] = ApiClient.convertToType(data['groups'], [GroupRef]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/FieldRef>} fields
    */
    fields = undefined;
    /**
    * @member {Array.<module:model/ComponentRef>} components
    */
    components = undefined;
    /**
    * @member {Array.<module:model/GroupRef>} groups
    */
    groups = undefined;








}


