/**
 * Orchestra API
 * API to edit FIX Orchestra (machine readable rules of engagement) specification version 1.0 RC3
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Trigger model module.
* @module model/Trigger
* @version 1.0.1
*/
export default class Trigger {
    /**
    * Constructs a new <code>Trigger</code>.
    * @alias module:model/Trigger
    * @class
    * @param stateMachine {String} name of StateMachine
    * @param actor {String} name of the Actor that owns the StateMachine
    * @param name {String} name of Transition to invoke
    */

    constructor(stateMachine, actor, name) {
        

        
        

        this['stateMachine'] = stateMachine;this['actor'] = actor;this['name'] = name;

        
    }

    /**
    * Constructs a <code>Trigger</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Trigger} obj Optional instance to populate.
    * @return {module:model/Trigger} The populated <code>Trigger</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Trigger();

            
            
            

            if (data.hasOwnProperty('stateMachine')) {
                obj['stateMachine'] = ApiClient.convertToType(data['stateMachine'], 'String');
            }
            if (data.hasOwnProperty('actor')) {
                obj['actor'] = ApiClient.convertToType(data['actor'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
    * name of StateMachine
    * @member {String} stateMachine
    */
    stateMachine = undefined;
    /**
    * name of the Actor that owns the StateMachine
    * @member {String} actor
    */
    actor = undefined;
    /**
    * name of Transition to invoke
    * @member {String} name
    */
    name = undefined;








}


